services:
  llama-server:
    build: .
    image: ghcr.io/dontdrinkandroot/llama-cpp.docker:latest
    env_file:
      - .env
    ports:
      - "${PORT:-8080}:8080"
    volumes:
      - models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  models:
